apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-account-migration-worker-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"